import os

APP_VER = 0.1
APP_NAME = "Screen Pulse"
APP_ICON = "ScreenPulseIcon.ico"

WORKING_DIR = os.getenv('APPDATA') + "\\" + APP_NAME
TRANSFER_DIR = WORKING_DIR + "\\Transfer"
TRANSFER_FRAMES_MAX_DEFAULT = 50
JPG_QUALITY = 75
SHARPENING = 1.5
SCALING = "Fit"
INVERT = False
RESAMPLE = "LANCZOS"

XOFF = "XOFF"
YOFF = "YOFF"
ZOOM_SCALE = "SCALE"

IMAGE_RECIEVE_FILE_NAME = "\\recieved.jpg"
IMAGE_CAPTURE_FILE_NAME = "\\capture.jpg"
CONFIG_NAME = "\\" + APP_NAME + " Config.ini"

FAILED_ATTEMPT_MAX = 5
CONNECTION_TIMEOUT_SECONDS = 6

#miliseconds
REFRESH_RATE_DEF = 2000
REFRESH_RATE_MIN = 200
DEFAULT_IP = "127.0.0.1"
DEFAULT_PORT = 9999